# Build website and serve HTML at localhost:4000
# Run with:
# docker compose up
# Run link tests with:
# docker compose run jekyll bundle exec rake test
# and:
# docker compose run jekyll bundle exec rake test_paper_links
services:
  jekyll:
    image: jekyll-site:latest
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/_site
    ports:
      - "4000:4000"
    command: bundle exec jekyll serve --host 0.0.0.0 --watch
